reference: http://www.objc.io/issue-6/travis-ci.html
language: objective-c
cache: bundler
before_install:
  - brew update
  - brew upgrade xctool
script:
- xctool test -workspace Example/DDDKeychainWrapper.xcworkspace -scheme DDDKeychainWrapper -sdk iphonesimulator7.1 ONLY_ACTIVE_ARCH=NO
